/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Username = IDL.Text;
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const Order = IDL.Record({
  'status' : IDL.Text,
  'couponCode' : IDL.Opt(IDL.Text),
  'paymentMethod' : IDL.Text,
  'deliveryEmail' : IDL.Text,
  'customerUsername' : Username,
  'orderId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'itemName' : IDL.Text,
  'paymentReference' : IDL.Text,
  'price' : IDL.Nat,
});
export const Membership = IDL.Record({
  'paymentMethod' : IDL.Text,
  'expiresAt' : IDL.Int,
  'customerUsername' : Username,
  'purchasedAt' : IDL.Int,
  'membershipId' : IDL.Nat,
  'paymentReference' : IDL.Text,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Nat,
});
export const PaymentSettings = IDL.Record({
  'bitcoinWallet' : IDL.Text,
  'ethereumWallet' : IDL.Text,
  'xboxInstructions' : IDL.Text,
  'etsyInstructions' : IDL.Text,
  'amazonInstructions' : IDL.Text,
  'paypalEmail' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Ad = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'adType' : IDL.Text,
});
export const Coupon = IDL.Record({
  'discountValue' : IDL.Nat,
  'code' : IDL.Text,
  'discountType' : IDL.Text,
  'usedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attachFileToProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Nat],
      [],
    ),
  'checkActiveMembership' : IDL.Func([Username], [IDL.Bool], ['query']),
  'createAd' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createCoupon' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'createPackage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteAd' : IDL.Func([IDL.Nat], [], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [], []),
  'deletePackage' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'downloadProductFile' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat8)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerOrders' : IDL.Func([Username], [IDL.Vec(Order)], ['query']),
  'getMembershipStatus' : IDL.Func(
      [Username],
      [IDL.Opt(Membership)],
      ['query'],
    ),
  'getPackage' : IDL.Func([IDL.Nat], [IDL.Opt(Package)], ['query']),
  'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettings)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
  'listActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'listAllAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
  'listAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'listAllMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
  'listAllOrders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Username, IDL.Vec(Order)))],
      ['query'],
    ),
  'listAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductFiles' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'fileName' : IDL.Text,
            'fileType' : IDL.Text,
            'fileId' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'listProductFilesAdmin' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'fileName' : IDL.Text,
            'fileType' : IDL.Text,
            'fileId' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'placeOrder' : IDL.Func(
      [
        Username,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'purchaseMembership' : IDL.Func(
      [Username, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeFileFromProduct' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePaymentSettings' : IDL.Func([PaymentSettings], [], []),
  'updateAd' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateCoupon' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([Username, IDL.Nat, IDL.Text], [], []),
  'updatePackage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Bool],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'validateCoupon' : IDL.Func(
      [IDL.Text, Username],
      [IDL.Record({ 'soloUse' : IDL.Bool, 'coupon' : Coupon })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Username = IDL.Text;
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  const Order = IDL.Record({
    'status' : IDL.Text,
    'couponCode' : IDL.Opt(IDL.Text),
    'paymentMethod' : IDL.Text,
    'deliveryEmail' : IDL.Text,
    'customerUsername' : Username,
    'orderId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'itemName' : IDL.Text,
    'paymentReference' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Membership = IDL.Record({
    'paymentMethod' : IDL.Text,
    'expiresAt' : IDL.Int,
    'customerUsername' : Username,
    'purchasedAt' : IDL.Int,
    'membershipId' : IDL.Nat,
    'paymentReference' : IDL.Text,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const PaymentSettings = IDL.Record({
    'bitcoinWallet' : IDL.Text,
    'ethereumWallet' : IDL.Text,
    'xboxInstructions' : IDL.Text,
    'etsyInstructions' : IDL.Text,
    'amazonInstructions' : IDL.Text,
    'paypalEmail' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Ad = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'adType' : IDL.Text,
  });
  const Coupon = IDL.Record({
    'discountValue' : IDL.Nat,
    'code' : IDL.Text,
    'discountType' : IDL.Text,
    'usedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attachFileToProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Nat],
        [],
      ),
    'checkActiveMembership' : IDL.Func([Username], [IDL.Bool], ['query']),
    'createAd' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createCoupon' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'createPackage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteAd' : IDL.Func([IDL.Nat], [], []),
    'deleteCoupon' : IDL.Func([IDL.Text], [], []),
    'deletePackage' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'downloadProductFile' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat8)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerOrders' : IDL.Func([Username], [IDL.Vec(Order)], ['query']),
    'getMembershipStatus' : IDL.Func(
        [Username],
        [IDL.Opt(Membership)],
        ['query'],
      ),
    'getPackage' : IDL.Func([IDL.Nat], [IDL.Opt(Package)], ['query']),
    'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettings)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
    'listActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'listAllAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
    'listAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'listAllMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
    'listAllOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Username, IDL.Vec(Order)))],
        ['query'],
      ),
    'listAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductFiles' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'fileName' : IDL.Text,
              'fileType' : IDL.Text,
              'fileId' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'listProductFilesAdmin' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'fileName' : IDL.Text,
              'fileType' : IDL.Text,
              'fileId' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'placeOrder' : IDL.Func(
        [
          Username,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'purchaseMembership' : IDL.Func(
        [Username, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeFileFromProduct' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePaymentSettings' : IDL.Func([PaymentSettings], [], []),
    'updateAd' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateCoupon' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([Username, IDL.Nat, IDL.Text], [], []),
    'updatePackage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Bool],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'validateCoupon' : IDL.Func(
        [IDL.Text, Username],
        [IDL.Record({ 'soloUse' : IDL.Bool, 'coupon' : Coupon })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };