/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'status' : string,
  'paymentMethod' : string,
  'customerUsername' : Username,
  'orderId' : bigint,
  'timestamp' : bigint,
  'itemName' : string,
  'paymentReference' : string,
  'price' : bigint,
}
export interface Package {
  'id' : bigint,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'price' : bigint,
}
export interface PaymentSettings {
  'bitcoinWallet' : string,
  'ethereumWallet' : string,
  'xboxInstructions' : string,
  'etsyInstructions' : string,
  'amazonInstructions' : string,
  'paypalEmail' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface UserProfile { 'username' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPackage' : ActorMethod<
    [string, string, bigint, Array<string>],
    bigint
  >,
  'createProduct' : ActorMethod<
    [string, string, bigint, string, string],
    bigint
  >,
  'deletePackage' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[Username], Array<Order>>,
  'getPackage' : ActorMethod<[bigint], [] | [Package]>,
  'getPaymentSettings' : ActorMethod<[], [] | [PaymentSettings]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivePackages' : ActorMethod<[], Array<Package>>,
  'listAllOrders' : ActorMethod<[], Array<[Username, Array<Order>]>>,
  'listAvailableProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<
    [Username, string, bigint, string, string],
    bigint
  >,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePaymentSettings' : ActorMethod<[PaymentSettings], undefined>,
  'updateOrderStatus' : ActorMethod<[Username, bigint, string], undefined>,
  'updatePackage' : ActorMethod<
    [bigint, string, string, bigint, Array<string>, boolean],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];